export const COUNTRIES = [
  {name: 'Афганистан', code: 'AF'},
  {name: 'Албания', code: 'AL'},
  {name: 'Алжир', code: 'DZ'},
  {name: 'Американское Самоа', code: 'AS'},
  {name: 'Андорра', code: 'AD'},
  {name: 'Ангола', code: 'AO'},
  {name: 'Антигуа и Барбуда', code: 'AG'},
  {name: 'Аргентина', code: 'AR'},
  {name: 'Армения', code: 'AM'},
  {name: 'Австралия', code: 'AU'},
  {name: 'Австрия', code: 'AT'},
  {name: 'Азербайджан', code: 'AZ'},
  {name: 'Багамы', code: 'BS'},
  {name: 'Бахрейн', code: 'BH'},
  {name: 'Бангладеш', code: 'BD'},
  {name: 'Барбадос', code: 'BB'},
  {name: 'Беларусь', code: 'BY'},
  {name: 'Бельгия', code: 'BE'},
  {name: 'Белиз', code: 'BZ'},
  {name: 'Бенин', code: 'BJ'},
  {name: 'Бермуды', code: 'BM'},
  {name: 'Бутан', code: 'BT'},
  {name: 'Боливия', code: 'BO'},
  {name: 'Босния и Герцеговина', code: 'BA'},
  {name: 'Ботсвана', code: 'BW'},
  {name: 'Бразилия', code: 'BR'},
  {name: 'Бруней', code: 'BN'},
  {name: 'Болгария', code: 'BG'},
  {name: 'Буркина-Фасо', code: 'BF'},
  {name: 'Бурунди', code: 'BI'},
  {name: 'Кабо-Верде', code: 'CV'},
  {name: 'Камбоджа', code: 'KH'},
  {name: 'Камерун', code: 'CM'},
  {name: 'Канада', code: 'CA'},
  {name: 'ЦАР', code: 'CF'},
  {name: 'Чад', code: 'TD'},
  {name: 'Чили', code: 'CL'},
  {name: 'Китай', code: 'CN'},
  {name: 'Колумбия', code: 'CO'},
  {name: 'Коморы', code: 'KM'},
  {name: 'Конго', code: 'CG'},
  {name: 'Коста-Рика', code: 'CR'},
  {name: 'Хорватия', code: 'HR'},
  {name: 'Куба', code: 'CU'},
  {name: 'Кипр', code: 'CY'},
  {name: 'Чехия', code: 'CZ'},
  {name: 'Дания', code: 'DK'},
  {name: 'Джибути', code: 'DJ'},
  {name: 'Доминика', code: 'DM'},
  {name: 'Доминиканская Республика', code: 'DO'},
  {name: 'Эквадор', code: 'EC'},
  {name: 'Египет', code: 'EG'},
  {name: 'Сальвадор', code: 'SV'},
  {name: 'Экваториальная Гвинея', code: 'GQ'},
  {name: 'Эритрея', code: 'ER'},
  {name: 'Эстония', code: 'EE'},
  {name: 'Эсватини', code: 'SZ'},
  {name: 'Эфиопия', code: 'ET'},
  {name: 'Фиджи', code: 'FJ'},
  {name: 'Финляндия', code: 'FI'},
  {name: 'Франция', code: 'FR'},
  {name: 'Габон', code: 'GA'},
  {name: 'Гамбия', code: 'GM'},
  {name: 'Грузия', code: 'GE'},
  {name: 'Германия', code: 'DE'},
  {name: 'Гана', code: 'GH'},
  {name: 'Греция', code: 'GR'},
  {name: 'Гренада', code: 'GD'},
  {name: 'Гватемала', code: 'GT'},
  {name: 'Гвинея', code: 'GN'},
  {name: 'Гвинея-Бисау', code: 'GW'},
  {name: 'Гайана', code: 'GY'},
  {name: 'Гаити', code: 'HT'},
  {name: 'Гондурас', code: 'HN'},
  {name: 'Венгрия', code: 'HU'},
  {name: 'Исландия', code: 'IS'},
  {name: 'Индия', code: 'IN'},
  {name: 'Индонезия', code: 'ID'},
  {name: 'Иран', code: 'IR'},
  {name: 'Ирак', code: 'IQ'},
  {name: 'Ирландия', code: 'IE'},
  {name: 'Израиль', code: 'IL'},
  {name: 'Италия', code: 'IT'},
  {name: 'Кот-д’Ивуар', code: 'CI'},
  {name: 'Ямайка', code: 'JM'},
  {name: 'Япония', code: 'JP'},
  {name: 'Иордания', code: 'JO'},
  {name: 'Казахстан', code: 'KZ'},
  {name: 'Кения', code: 'KE'},
  {name: 'Кирибати', code: 'KI'},
  {name: 'Кувейт', code: 'KW'},
  {name: 'Кыргызстан', code: 'KG'},
  {name: 'Лаос', code: 'LA'},
  {name: 'Латвия', code: 'LV'},
  {name: 'Ливан', code: 'LB'},
  {name: 'Лесото', code: 'LS'},
  {name: 'Либерия', code: 'LR'},
  {name: 'Ливия', code: 'LY'},
  {name: 'Лихтенштейн', code: 'LI'},
  {name: 'Литва', code: 'LT'},
  {name: 'Люксембург', code: 'LU'},
  {name: 'Мадагаскар', code: 'MG'},
  {name: 'Малави', code: 'MW'},
  {name: 'Малайзия', code: 'MY'},
  {name: 'Мальдивы', code: 'MV'},
  {name: 'Мали', code: 'ML'},
  {name: 'Мальта', code: 'MT'},
  {name: 'Маршалловы Острова', code: 'MH'},
  {name: 'Мавритания', code: 'MR'},
  {name: 'Маврикий', code: 'MU'},
  {name: 'Мексика', code: 'MX'},
  {name: 'Молдова', code: 'MD'},
  {name: 'Монако', code: 'MC'},
  {name: 'Монголия', code: 'MN'},
  {name: 'Черногория', code: 'ME'},
  {name: 'Марокко', code: 'MA'},
  {name: 'Мозамбик', code: 'MZ'},
  {name: 'Мьянма', code: 'MM'},
  {name: 'Намибия', code: 'NA'},
  {name: 'Науру', code: 'NR'},
  {name: 'Непал', code: 'NP'},
  {name: 'Нидерланды', code: 'NL'},
  {name: 'Новая Зеландия', code: 'NZ'},
  {name: 'Никарагуа', code: 'NI'},
  {name: 'Нигер', code: 'NE'},
  {name: 'Нигерия', code: 'NG'},
  {name: 'Северная Македония', code: 'MK'},
  {name: 'Норвегия', code: 'NO'},
  {name: 'Оман', code: 'OM'},
  {name: 'Пакистан', code: 'PK'},
  {name: 'Палау', code: 'PW'},
  {name: 'Палестина', code: 'PS'},
  {name: 'Панама', code: 'PA'},
  {name: 'Папуа — Новая Гвинея', code: 'PG'},
  {name: 'Парагвай', code: 'PY'},
  {name: 'Перу', code: 'PE'},
  {name: 'Филиппины', code: 'PH'},
  {name: 'Польша', code: 'PL'},
  {name: 'Португалия', code: 'PT'},
  {name: 'Катар', code: 'QA'},
  {name: 'Румыния', code: 'RO'},
  {name: 'Россия', code: 'RU'},
  {name: 'Руанда', code: 'RW'},
  {name: 'Сент-Китс и Невис', code: 'KN'},
  {name: 'Сент-Люсия', code: 'LC'},
  {name: 'Сент-Винсент и Гренадины', code: 'VC'},
  {name: 'Самоа', code: 'WS'},
  {name: 'Сан-Марино', code: 'SM'},
  {name: 'Сан-Томе и Принсипи', code: 'ST'},
  {name: 'Саудовская Аравия', code: 'SA'},
  {name: 'Сенегал', code: 'SN'},
  {name: 'Сербия', code: 'RS'},
  {name: 'Сейшельские Острова', code: 'SC'},
  {name: 'Сьерра-Леоне', code: 'SL'},
  {name: 'Сингапур', code: 'SG'},
  {name: 'Словакия', code: 'SK'},
  {name: 'Словения', code: 'SI'},
  {name: 'Соломоновы Острова', code: 'SB'},
  {name: 'Сомали', code: 'SO'},
  {name: 'Южно-Африканская Республика', code: 'ZA'},
  {name: 'Южная Корея', code: 'KR'},
  {name: 'Южный Судан', code: 'SS'},
  {name: 'Испания', code: 'ES'},
  {name: 'Шри-Ланка', code: 'LK'},
  {name: 'Судан', code: 'SD'},
  {name: 'Суринам', code: 'SR'},
  {name: 'Швеция', code: 'SE'},
  {name: 'Швейцария', code: 'CH'},
  {name: 'Сирия', code: 'SY'},
  {name: 'Таджикистан', code: 'TJ'},
  {name: 'Танзания', code: 'TZ'},
  {name: 'Таиланд', code: 'TH'},
  {name: 'Тимор-Лесте', code: 'TL'},
  {name: 'Того', code: 'TG'},
  {name: 'Тонга', code: 'TO'},
  {name: 'Тринидад и Тобаго', code: 'TT'},
  {name: 'Тунис', code: 'TN'},
  {name: 'Турция', code: 'TR'},
  {name: 'Туркмения', code: 'TM'},
  {name: 'Тувалу', code: 'TV'},
  {name: 'Уганда', code: 'UG'},
  {name: 'Украина', code: 'UA'},
  {name: 'ОАЭ', code: 'AE'},
  {name: 'Великобритания', code: 'GB'},
  {name: 'США', code: 'US'},
  {name: 'Уругвай', code: 'UY'},
  {name: 'Узбекистан', code: 'UZ'},
  {name: 'Вануату', code: 'VU'},
  {name: 'Ватикан', code: 'VA'},
  {name: 'Венесуэла', code: 'VE'},
  {name: 'Вьетнам', code: 'VN'},
  {name: 'Йемен', code: 'YE'},
  {name: 'Замбия', code: 'ZM'},
  {name: 'Зимбабве', code: 'ZW'}
]
